version: '3.4'

networks:
    net:

services:

### MariaDb ########################################
    maria:
      build:
        context: ./db/mariadb
      container_name: mariadb
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root_psw1
        MYSQL_DATABASE: db1
        MYSQL_USER: user1
        MYSQL_PASSWORD: psw1
      volumes:
        - ./db/mysql-data:/var/log/mysql/
        - ./db/config:/etc/mysql/conf.d
      networks:
        - net


### ElasticSearch ########################################
    elasticsearch:
      build:
        context: ./elk/elasticsearch   
      container_name: elasticsearch
      volumes:
  #      - ./elk/elasticsearch:/usr/share/elasticsearch/data
        - elasticsearch:/usr/share/elasticsearch/data
      environment:        
        - bootstrap.memory_lock=true
        - discovery.type=single-node
      ulimits:
        memlock:
          soft: -1
          hard: -1
        nofile:
          soft: 65536
          hard: 65536
      ports:
        - "9200:9200"
        - "9300:9300"      
      networks:
        - net

### Logstash ##############################################
    logstash:
      build:
        context: ./elk/logstash
      container_name: logstash
      volumes:
        - ./elk/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
        - ./elk/logstash/pipeline/:/usr/share/logstash/pipeline
        - ./elk/logstash/testlogs:/usr/share/logstash/testlogs/
      ports:
        - "5044:5044"
      networks:
        - net
      depends_on:
        - elasticsearch

### Kibana ##############################################
    kibana:
      build:
        context: ./elk/kibana
      container_name: kibana
      ports:
        - "5601:5601"
      depends_on:
        - elasticsearch
      networks:
        - net


### Filebeat ##############################################
    filebeat:
      build:
        context: ./elk/filebeat/
      container_name: filebeat
      volumes:
#        - ./elk/filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
        - ./db/mysql-data/:/usr/share/filebeat/logs/
#        - ./test/:/usr/share/filebeat/
      environment:
        - strict.perms=false
      depends_on:
        - logstash
        - elasticsearch
        - kibana
      networks:
        - net

### MongoDB ##############################################
    mongo:
      image: mongo:3
      container_name: mongo
      volumes:
        - mongo_data:/data/db
      ports:
        - 27017:27017
      networks:
        - net

### Graylog ##############################################
    graylog:
      image: graylog/graylog:4.0
      container_name: graylog
      volumes:
        - "graylogjournal:/usr/share/graylog/data/journal"
        - "graylogconfig:/usr/share/graylog/data/config" # ADDED
      environment:
        # CHANGE ME (must be at least 16 characters)!
        - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
        # Password: admin
        - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
        - GRAYLOG_HTTP_EXTERNAL_URI=http://graylog:9000/
        - GRAYLOG_IS_MASTER=true
      entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
      ports:
        # Graylog web interface and REST API
        - 9000:9000
        # Syslog TCP
        - 1514:1514
        # Syslog UDP
        - 1514:1514/udp
        # GELF TCP
        - 12201:12201
        # GELF UDP
        - 12201:12201/udp
      links:
        - mongo
        - elasticsearch
      depends_on:
        - mongo
        - elasticsearch
      networks:
        - net

volumes:
    graylogjournal:
      driver: local
    graylogconfig: # ADDED
      driver: local # ADDED
    mongo_data:
      driver: local # ADDED
    elasticsearch:
      driver: local # ADDED